apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sales-predictor-monitor
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: sales-predictor
  endpoints:
    - port: "80"
      path: /metrics
      interval: 15s